
#ifndef CHESS_ENGINE_MACROS_H
#define CHESS_ENGINE_MACROS_H

#define NUMBER_IN_BOUNDS(NUMBER, MINIMUM, MAXIMUM) (NUMBER >= MINIMUM && NUMBER <= MAXIMUM)

#define MAX_NUMBER_VALUE(NUMBER1, NUMBER2) ((NUMBER2 > NUMBER1) ? NUMBER2 : NUMBER1)

#define MIN_NUMBER_VALUE(NUMBER1, NUMBER2) ((NUMBER2 < NUMBER1) ? NUMBER2 : NUMBER1)

#define PIECE_TYPE_EXISTS(TYPE) NUMBER_IN_BOUNDS(TYPE, 1, 6)

#define PIECE_TEAM_EXISTS(TEAM) ((TEAM == TEAM_WHITE) || (TEAM == TEAM_BLACK))

#define TEAM_WEIGHT_SCORE(SCORE, TEAM) ((TEAM == TEAM_BLACK) ? -SCORE : SCORE)

#define TEAM_SCORE_WEIGHT(TEAM) ((TEAM == TEAM_WHITE) ? 1 : -1)

#define TEAM_MATRIX_RANK(RANK, TEAM) ((TEAM == TEAM_WHITE) ? RANK : (BOARD_RANKS - RANK - 1))

#define MOVE_OFFSET_FACTOR(OFFSET) ((OFFSET == 0) ? 0 : ((OFFSET > 0) ? 1 : -1))

#define CLEAR_WHITE_KSIDE(CASTLE) (CASTLE & ~WHITE_KSIDE)
#define CLEAR_WHITE_QSIDE(CASTLE) (CASTLE & ~WHITE_QSIDE)
#define CLEAR_BLACK_KSIDE(CASTLE) (CASTLE & ~BLACK_KSIDE)
#define CLEAR_BLACK_QSIDE(CASTLE) (CASTLE & ~BLACK_QSIDE)

#define CLEAR_WHITE_CASTLE(CASTLE) (CASTLE & ~WHITE_KSIDE & ~WHITE_QSIDE)
#define CLEAR_BLACK_CASTLE(CASTLE) (CASTLE & ~BLACK_KSIDE & ~BLACK_QSIDE)

#endif
