
#ifndef ENGINE_POINT_MACROS_H
#define ENGINE_POINT_MACROS_H

#define MASK_POINT_RANK(POINT) (POINT & POINT_RANK_MASK)
#define MASK_POINT_FILE(POINT) (POINT & POINT_FILE_MASK)

#define POINT_SQAURE_WHITE(POINT) ((POINT_RANK_MACRO(POINT) + POINT_FILE_MACRO(POINT)) % 2 == 0)

#define CLEAR_POINT_RANK(POINT) (POINT & ~POINT_RANK_MASK)
#define CLEAR_POINT_FILE(POINT) (POINT & ~POINT_FILE_MASK)

#define POINT_RANK_MACRO(POINT) (MASK_POINT_RANK(POINT) >> POINT_RANK_SHIFT)
#define POINT_FILE_MACRO(POINT) (MASK_POINT_FILE(POINT) >> POINT_FILE_SHIFT)

#define RANK_POINT_MACRO(RANK) MASK_POINT_RANK((RANK << POINT_RANK_SHIFT))
#define FILE_POINT_MACRO(FILE) MASK_POINT_FILE((FILE << POINT_FILE_SHIFT))

#define ALLOC_POINT_RANK(POINT, RANK) (CLEAR_POINT_RANK(POINT) | MASK_POINT_RANK(RANK))
#define ALLOC_POINT_FILE(POINT, FILE) (CLEAR_POINT_FILE(POINT) | MASK_POINT_FILE(FILE))

#define POINT_INSIDE_BOARD(POINT) NUMBER_IN_BOUNDS(POINT, 0, BOARD_POINTS - 1)
#define POINTS_INSIDE_BOARD(POINT1, POINT2) (POINT_INSIDE_BOARD(POINT1) && POINT_INSIDE_BOARD(POINT2))

#define RANK_INSIDE_BOARD(RANK) NUMBER_IN_BOUNDS(RANK, 0, BOARD_RANKS - 1)
#define FILE_INSIDE_BOARD(FILE) NUMBER_IN_BOUNDS(FILE, 0, BOARD_FILES - 1)

#define RANK_FILE_INSIDE(RANK, FILE) (RANK_INSIDE_BOARD(RANK) && FILE_INSIDE_BOARD(FILE))

#define RANK_FILE_POINT(RANK, FILE) (RANK_POINT_MACRO(RANK) | FILE_POINT_MACRO(FILE))

#endif
